import type { Card } from "./types.js";

/**
 * Card catalog transcribed from `docs/game/cards-tier3-silver.md`,
 * `docs/game/cards-tier2-gold.md`, `docs/game/cards-tier1-diamond.md`,
 * `docs/game/locations.md`, `docs/game/origins.md` and
 * `docs/game/special-systems.md` (sourced from "1.4 BRUNO.pdf"). Keep this
 * file in sync with those docs.
 */
export const CARDS: Card[] = [
  // ---- Tier III / Silver Vault (p.1-2) ----
  {
    id: "t3-hush",
    name: "Hush I",
    type: "vault-silver",
    tags: [],
    effect: "Skip 2 players for 1 round.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-mitosis",
    name: "Mitosis I",
    type: "vault-silver",
    tags: [],
    effect: "+1 to 2 players.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-scrap-shot",
    name: "Scrap Shot I",
    type: "vault-silver",
    tags: [],
    effect: "Pick a player, +1 them and discard 1 card without seeing their cards.",
    source: "1.4 BRUNO.pdf p.1",
    status: "stable",
  },
  {
    id: "t3-trade-sector",
    name: "Trade Sector I",
    type: "vault-silver",
    tags: [],
    effect:
      "Switch 2 cards in your hand with any player without seeing their cards. If they have less than 2 cards, +1 them.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-disorder",
    name: "Disorder",
    type: "vault-silver",
    tags: [],
    effect: "Rearrange the order of players.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-imploded-clockwork",
    name: "Imploded Clockwork",
    type: "vault-silver",
    tags: [],
    effect: "Return played cards by 3 turns.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-prototype-z",
    name: "Prototype Z",
    type: "vault-silver",
    tags: [],
    effect: "Throw a coin, if it's heads skip yourself, otherwise +4 anyone.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-midas-touch",
    name: "Midas Touch",
    type: "vault-silver",
    tags: [],
    effect: "All players must play a yellow card, otherwise +4 them.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-spell-shield",
    name: "Spell Shield",
    type: "vault-silver",
    tags: ["special-passive"],
    effect:
      "You are not affected by the next special card you receive except from the Diamond Vault.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-future-market",
    name: "Future Market",
    type: "vault-silver",
    tags: [],
    effect: "Give 2 cards to any player and return the cards in 4 rounds.",
    playCondition: "To play, you must have 6+ cards.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-blitzkrieg",
    name: "Blitzkrieg",
    type: "vault-silver",
    tags: [],
    effect: "For 5 seconds you can draw as many cards as possible. [1 by 1 only].",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-accumulation",
    name: "Accumulation",
    type: "vault-silver",
    tags: ["special-passive"],
    effect: "Your next + card is x2.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-scavenge",
    name: "Scavenge",
    type: "vault-silver",
    tags: [],
    effect: "Discard 1-5 cards in your hand. Draw 1 for each card discarded.",
    source: "1.4 BRUNO.pdf p.1",
    status: "draft",
  },
  {
    id: "t3-upgrade",
    name: "Upgrade!",
    type: "vault-silver",
    tags: ["special-passive", "new"],
    effect: "Your next vault will be 1 tier higher. (Diamond Max).",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-green-tide",
    name: "Green Tide",
    type: "vault-silver",
    tags: ["special-passive", "new"],
    effect: "Double the cards of everyone after 15 rounds divided by 1.5.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-double-edged-sword",
    name: "Double Edged Sword",
    type: "vault-silver",
    tags: ["new"],
    effect: "+4 a player and +1 yourself.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-offerings",
    name: "Offerings",
    type: "vault-silver",
    tags: ["new"],
    effect: "Get a Silver Vault and +2 anyone.",
    playCondition: "To play, discard 3 draw [+] cards.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-investment",
    name: "Investment",
    type: "vault-silver",
    tags: ["passive", "new"],
    effect: "Each round, you may choose to draw an additional card.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-flash-flood",
    name: "Flash Flood",
    type: "vault-silver",
    tags: ["new"],
    effect: "All other players must play a blue card, otherwise +4 them.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-red-flag",
    name: "Red Flag",
    type: "vault-silver",
    tags: ["new"],
    effect: "All other players must play a red card, otherwise +4 them.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-green-thumb",
    name: "Green Thumb",
    type: "vault-silver",
    tags: ["new"],
    effect: "All other players must play a green card, otherwise +4 them.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-book-of-nostradamus",
    name: "Book of Nostradamus",
    type: "vault-silver",
    tags: ["passive", "new"],
    effect:
      "Predict the outcome of the game. Start with a Diamond Vault next game if you are correct.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-synchronize",
    name: "Synchronize!",
    type: "vault-silver",
    tags: ["new"],
    effect: "Play the last vault card that the last player played.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-double-trouble",
    name: "Double Trouble",
    type: "vault-silver",
    tags: ["new"],
    effect:
      "Ally with another player forever, go to their left side. Both of you can share your cards.",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-sunder",
    name: "Sunder",
    type: "vault-silver",
    tags: ["new"],
    effect: "Pick a player, (effect text unreadable in PDF).",
    source: "1.4 BRUNO.pdf p.2",
    status: "draft",
  },
  {
    id: "t3-liquidation",
    name: "Liquidation",
    type: "vault-silver",
    tags: ["tentative", "new"],
    effect: "You can't draw in the deck for 2 rounds. You are skipped instead.",
    source: "1.4 BRUNO.pdf p.2",
    status: "tentative",
  },
  {
    id: "t3-all-in",
    name: "All In",
    type: "vault-silver",
    tags: ["tentative", "new"],
    effect: "Get 2 Diamond Vaults. After 3 rounds, +15 and discard your Vaults.",
    source: "1.4 BRUNO.pdf p.2-3",
    status: "tentative",
  },

  // ---- Tier II / Gold Vault (p.3-4) ----
  {
    id: "t2-hush",
    name: "Hush II",
    type: "vault-gold",
    tags: [],
    effect: "Skip 2 random players for 3 turns.",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "t2-mitosis",
    name: "Mitosis II",
    type: "vault-gold",
    tags: [],
    effect: "+2 to 2 players.",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "t2-scrap-shot",
    name: "Scrap Shot II",
    type: "vault-gold",
    tags: [],
    effect: "Pick a player, +3 them and discard 3 cards without seeing their cards.",
    source: "1.4 BRUNO.pdf p.3",
    status: "stable",
  },
  {
    id: "t2-force-of-will",
    name: "Force of Will",
    type: "vault-gold",
    tags: [],
    effect: "Pick a player to play any + card, if they don't +5 them.",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "t2-trade-sector",
    name: "Trade Sector II",
    type: "vault-gold",
    tags: [],
    effect:
      "Switch 3 cards in your hand with anyone without seeing their cards. If they have less than 3 cards, +2 them.",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "t2-future-sight",
    name: "Future Sight",
    type: "vault-gold",
    tags: [],
    effect: "See the cards of a player.",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "t2-jettison",
    name: "Jettison",
    type: "vault-gold",
    tags: [],
    effect: "Pick a color, discard all of those cards with the same color.",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "t2-augmented-zep-y",
    name: "Augmented Zep-y",
    type: "vault-gold",
    tags: [],
    effect: "Throw a coin, if it's heads skip yourself for 2 turns, otherwise +6 anyone.",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "t2-card-a-palooza",
    name: "Card-a-Palooza",
    type: "vault-gold",
    tags: [],
    effect:
      "All players shuffle their cards with each other and return with the same amount of cards.",
    source: "1.4 BRUNO.pdf p.3",
    status: "stable",
  },
  {
    id: "t2-spell-counter",
    name: "Spell Counter",
    type: "vault-gold",
    tags: ["special-passive"],
    effect: "Return the next special card effect you receive to the sender, except Diamond Vault.",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "t2-most-wanted",
    name: "Most Wanted",
    type: "vault-gold",
    tags: ["passive"],
    effect: "Pick a player, that player will be +1 every time they play a blue or red card.",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "t2-ruin",
    name: "Ruin",
    type: "vault-gold",
    tags: ["new"],
    effect: "Get a Gold Vault and +3 2 enemy players.",
    playCondition: "To play, discard a total of 7 red or yellow cards.",
    source: "1.4 BRUNO.pdf p.3-4",
    status: "draft",
  },
  {
    id: "t2-foedus",
    name: "Foedus",
    type: "vault-gold",
    tags: ["special-passive"],
    effect:
      "Pick a player to ally with for 5 rounds. If one of you wins, reduce the cards of the other player to 1.",
    source: "1.4 BRUNO.pdf p.4",
    status: "draft",
  },
  {
    id: "t2-cruelty",
    name: "Cruelty",
    type: "vault-gold",
    tags: ["special-passive"],
    effect: "Pick 2 players, neither of them can win until both of their hands are reduced to 1.",
    source: "1.4 BRUNO.pdf p.4",
    status: "draft",
  },
  {
    id: "t2-parasitism",
    name: "Parasitism",
    type: "vault-gold",
    tags: ["passive"],
    effect:
      "Pick a player, whenever they play a green card, discard a card from your hand. Discard your cards starting in 9-0, switch color, skip, reverse, +2, +4, and Tier III-I.",
    source: "1.4 BRUNO.pdf p.4",
    status: "draft",
  },
  {
    id: "t2-vault-hunter",
    name: "Vault Hunter",
    type: "vault-gold",
    tags: [],
    effect: "Pick 1-3 players and steal up to 2 vault cards from them.",
    source: "1.4 BRUNO.pdf p.4",
    status: "stable",
  },
  {
    id: "t2-rummage",
    name: "Rummage",
    type: "vault-gold",
    tags: [],
    effect: "Discard your hand. Draw 1 for each card discarded. It's your turn again.",
    source: "1.4 BRUNO.pdf p.4",
    status: "draft",
  },
  {
    id: "t2-triple-threat",
    name: "Triple Threat",
    type: "vault-gold",
    tags: [],
    effect:
      "Ally with 2 players forever, go between them. All of you share your cards and punishments.",
    source: "1.4 BRUNO.pdf p.4",
    status: "draft",
  },
  {
    id: "t2-twice-than-one",
    name: "Twice than One!",
    type: "vault-gold",
    tags: ["tentative"],
    effect: "Get 2 Silver Vaults.",
    source: "1.4 BRUNO.pdf p.4",
    status: "tentative",
  },
  {
    id: "t2-sacrificial-lamb",
    name: "Sacrificial Lamb",
    type: "vault-gold",
    tags: ["tentative"],
    effect: "Discard 2 special cards to draw 10.",
    source: "1.4 BRUNO.pdf p.4",
    status: "tentative",
  },
  {
    id: "t2-flight-of-icarus",
    name: "Flight of Icarus",
    type: "vault-gold",
    tags: ["tentative"],
    effect: "(effect unreadable in PDF).",
    source: "1.4 BRUNO.pdf p.4",
    status: "tentative",
  },

  // ---- Tier I / Diamond Vault (p.4-8) ----
  {
    id: "t1-global-silence",
    name: "Global Silence",
    type: "vault-diamond",
    tags: [],
    effect: "Skip all enemy players for 3 rounds.",
    source: "1.4 BRUNO.pdf p.4",
    status: "draft",
  },
  {
    id: "t1-meiosis",
    name: "Meiosis",
    type: "vault-diamond",
    tags: [],
    effect: "+3 to all enemy players.",
    source: "1.4 BRUNO.pdf p.4",
    status: "draft",
  },
  {
    id: "t1-scrapheap",
    name: "Scrapheap",
    type: "vault-diamond",
    tags: [],
    effect:
      "+1 to all enemy players and discard a total of 1 - 7 cards to any enemy players while seeing their cards.",
    source: "1.4 BRUNO.pdf p.4",
    status: "draft",
  },
  {
    id: "t1-plunder",
    name: "Plunder",
    type: "vault-diamond",
    tags: [],
    effect: "Pick an enemy player, +3 them and steal 1 - 3 cards while seeing their cards.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-suicide",
    name: "Suicide",
    type: "vault-diamond",
    tags: [],
    effect: "+12 to yourself and to any enemy player.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-all-seeing-eye",
    name: "All Seeing Eye",
    type: "vault-diamond",
    tags: ["passive"],
    effect: "See the cards of everyone and pick one to see their cards forever.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-jack-of-all-trades",
    name: "Jack of All Trades",
    type: "vault-diamond",
    tags: [],
    effect:
      "+1 a random enemy player, skip a random enemy player for 1 round, discard 1 card from any enemy player while seeing their cards and see all the cards of a random enemy player.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-g-switch",
    name: "G-Switch",
    type: "vault-diamond",
    tags: [],
    effect: "Switch hands with anyone.",
    source: "1.4 BRUNO.pdf p.5",
    status: "stable",
  },
  {
    id: "t1-rewind",
    name: "Rewind",
    type: "vault-diamond",
    tags: [],
    effect: "Reset the game. [4 or more players only].",
    playCondition: "To play, anyone must play a total of 7 Diamond Vaults.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-ticket-to-paradise",
    name: "Ticket to Paradise",
    type: "vault-diamond",
    tags: ["special-passive"],
    effect:
      "After you win, pick a player and reduce their cards to 1. If you have 6+ cards, reduce your cards to 4. Discard your cards starting in 9-0, switch color, skip, reverse, +2, +4, and Tier III-I.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-zephyr",
    name: "Zephyr",
    type: "vault-diamond",
    tags: ["passive"],
    effect:
      "You can play 2 cards in your turn, some special cards have effects and +2 to all enemy players.",
    playCondition: "To play, Prototype Z and Augmented Zep-y must be played by you.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-tyranny",
    name: "Tyranny",
    type: "vault-diamond",
    tags: ["passive"],
    effect: "Whenever you skip an enemy player +3 them. Skip the next player.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-equality",
    name: "Equality",
    type: "vault-diamond",
    tags: ["passive"],
    effect: "Everytime you play an even no. card, +2 to a random enemy player.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-last-stand",
    name: "Last Stand",
    type: "vault-diamond",
    tags: ["special-passive"],
    effect: "If you would lose, discard your hand and +4, while the opposing player +5.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-divinity",
    name: "Divinity",
    type: "vault-diamond",
    tags: ["passive"],
    effect: "You are not affected by anything except Diamond Vault.",
    source: "1.4 BRUNO.pdf p.5",
    status: "draft",
  },
  {
    id: "t1-arise",
    name: "Arise",
    type: "vault-diamond",
    tags: [],
    effect: "Return a player who has won the game, +2 and skip them.",
    source: "1.4 BRUNO.pdf p.5-6",
    status: "draft",
  },
  {
    id: "t1-bootleg",
    name: "Bootleg",
    type: "vault-diamond",
    tags: [],
    effect:
      "Pick a power from the artifact that you crafted. These powers cannot be destroyed. Find Boot and Leg.",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-maim",
    name: "Maim",
    type: "vault-diamond",
    tags: ["passive"],
    effect:
      "All enemies with more than 2 cards gain Bleed, every 2 cards added after that, gain another Bleed. When enemies have 5 stacks of Bleed, +20 them and reset the Bleed.",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-cutthroat",
    name: "Cutthroat",
    type: "vault-diamond",
    tags: ["special-passive"],
    effect:
      "All enemy players cannot use special cards anymore. Their special cards are now Deadweight. Remove all Deadweight once everyone's total cards is 30. If they aren't removed in 20 rounds, +4 them for each Deadweight they are holding and discard it.",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-silver-tongue",
    name: "Silver Tongue",
    type: "vault-diamond",
    tags: ["passive"],
    effect:
      "No one can play their last card if you're still in the game. Switch everyone's hand clockwise every round. Everyone can see EVERYONE'S cards.",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-finality",
    name: "Finality",
    type: "vault-diamond",
    tags: [],
    effect: "When you have all 0, kill all enemies and win the game. [Blue, Red, Green, Yellow].",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-greed-is-good",
    name: "Greed is Good",
    type: "vault-diamond",
    tags: ["passive"],
    effect: "Win by getting exactly 20 cards. When you draw a card, remove a card from your hand.",
    playCondition: "To play, you must have exactly 15 cards. You cannot be Arised.",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-doomsday-button",
    name: "Doomsday Button",
    type: "vault-diamond",
    tags: ["passive"],
    effect: "Win in 60 rounds. Skip yourself for 30 rounds.",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-cosmic-alignment",
    name: "Cosmic Alignment",
    type: "vault-diamond",
    tags: ["passive", "new"],
    effect:
      "Win by getting blue numbered cards from 0 to 9. Your hand is now limited to 11 cards, excess cards are discarded. You cannot be Arised.",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-all-is-fair",
    name: "All is Fair in Love and War",
    type: "vault-diamond",
    tags: [],
    effect: "Destroy all enemy passives [P] and +4 them.",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-scourge",
    name: "Scourge",
    type: "vault-diamond",
    tags: ["passive"],
    effect:
      "Pick a player to infect, after that player reaches 1 card, +1 to them and +2 to all other enemies. Infect the next player after them until it reaches the host again. You can't get infected.",
    source: "1.4 BRUNO.pdf p.6",
    status: "draft",
  },
  {
    id: "t1-prayers",
    name: "Prayers",
    type: "vault-diamond",
    tags: ["passive"],
    effect:
      "All your red cards have +1. Gain additional + if you played the following before prayers; Offerings, +1. Path to Ruin, +2. Both, +4.",
    source: "1.4 BRUNO.pdf p.6-7",
    status: "draft",
  },
  {
    id: "t1-unnamed-card",
    name: "Unnamed Card",
    type: "vault-diamond",
    tags: [],
    effect:
      "All your no. cards have + depending on your no. card. Non no. cards are +2. It's your turn again. Enemy players that have 25+ cards are killed. +4 EVERYONE.",
    playCondition: "To play, ???",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-ultimate-machine-form",
    name: "Ultimate Machine Form",
    type: "vault-diamond",
    tags: ["tentative"],
    effect: "All your moves are now doubled.",
    source: "1.4 BRUNO.pdf p.7",
    status: "tentative",
  },
  {
    id: "t1-thrice-than-twice",
    name: "Thrice Than Twice!",
    type: "vault-diamond",
    tags: ["tentative"],
    effect: "Get 3 Silver Vaults.",
    source: "1.4 BRUNO.pdf p.7",
    status: "tentative",
  },
  {
    id: "t1-mega-upgrade",
    name: "Mega Upgrade!",
    type: "vault-diamond",
    tags: [],
    effect: "Your next Diamond Vault will be upgraded, shuffle me back into the deck.",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-sloth",
    name: "Sloth",
    type: "vault-diamond",
    tags: [],
    effect: "Skip all enemies for 20 rounds.",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-genesis",
    name: "Genesis",
    type: "vault-diamond",
    tags: [],
    effect:
      "+6 to all enemy players. The enemy with the most cards is skipped depending on the no. of cards that they have.",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-scrapstorm",
    name: "Scrapstorm",
    type: "vault-diamond",
    tags: [],
    effect:
      "Pick a total of 1 - 15 cards to any enemy players while seeing their cards, then give them to other players.",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-avarice",
    name: "Avarice",
    type: "vault-diamond",
    tags: [],
    effect:
      "+2 to all players then steal a total of 1-5 cards to any enemy players while seeing their cards.",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-damnation",
    name: "Damnation",
    type: "vault-diamond",
    tags: [],
    effect: "+1 to yourself and +23 to an enemy player.",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-omniscient",
    name: "Omniscient",
    type: "vault-diamond",
    tags: ["passive"],
    effect: "See all the cards permanently and skip anyone for 5 rounds.",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-jack-master",
    name: "Jack of all Trades, Master of Some",
    type: "vault-diamond",
    tags: [],
    effect:
      "+4 2 enemy players, skip 2 enemy players for 4 rounds, discard 1-4 cards from 2 enemy players while seeing their cards and see all the cards of 2 enemy players.",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-envy",
    name: "Envy",
    type: "vault-diamond",
    tags: [],
    effect: "Switch hands with anyone and do it again to another pair of players.",
    source: "1.4 BRUNO.pdf p.7",
    status: "draft",
  },
  {
    id: "t1-unnamed-morning-star",
    name: "Unnamed Card (Morning Star analog)",
    type: "vault-diamond",
    tags: [],
    effect: "In 15 rounds, kill all enemy players with less than 20 RED cards.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },
  {
    id: "t1-evening-star",
    name: "The Evening Star",
    type: "vault-diamond",
    tags: [],
    effect:
      "Revive all winners and +10 all enemy players. In 15 rounds, kill all enemy players with less than 20 BLUE cards.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },
  {
    id: "t1-dawns-triumph",
    name: "Dawn's Triumph",
    type: "vault-diamond",
    tags: [],
    effect: "Kill all enemy players with less than 5 BLUE or RED cards.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },

  // ---- Locations (p.8) ----
  {
    id: "loc-fields",
    name: "Fields",
    type: "location",
    tags: [],
    effect: "All players draw 1 card at the beginning of the game.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },
  {
    id: "loc-silver-prairie",
    name: "Silver Prairie",
    type: "location",
    tags: [],
    effect: "You can trade a card with everyone only once.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },
  {
    id: "loc-desert",
    name: "Desert",
    type: "location",
    tags: [],
    effect: "A random player is skipped at the beginning of the game.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },
  {
    id: "loc-scorched-earth",
    name: "Scorched Earth",
    type: "location",
    tags: [],
    effect:
      "If the player has only 1 card left, the player with the most cards gives them 3 cards and skip them.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },
  {
    id: "loc-ocean",
    name: "Ocean",
    type: "location",
    tags: [],
    effect: "The first vault any player will play is a Diamond Vault.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },
  {
    id: "loc-abyssal-depths",
    name: "Abyssal Depths",
    type: "location",
    tags: [],
    effect: "All vaults are Diamond Vault.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },
  {
    id: "loc-volcano",
    name: "Volcano",
    type: "location",
    tags: [],
    effect: "Silver and Gold effects are doubled.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },
  {
    id: "loc-hell-gate",
    name: "Hell Gate",
    type: "location",
    tags: [],
    effect: "No explicit effect text is available; it is bound to Diamond Vault.",
    source: "1.4 BRUNO.pdf p.8",
    status: "draft",
  },

  // ---- Origin Vaults (p.9) ----
  {
    id: "origin-vault-keeper",
    name: "Vault Keeper",
    type: "origin",
    tags: [],
    effect: "Greed is good. Get a Gold Vault at the start of the game.",
    source: "1.4 BRUNO.pdf p.9",
    status: "draft",
  },
  {
    id: "origin-technomancer",
    name: "Technomancer",
    type: "origin",
    tags: [],
    effect:
      "Technology at its finest. Your vaults have a chance to get another vault of the same type. 43% Silver, 20% Gold, 10% Diamond.",
    source: "1.4 BRUNO.pdf p.9",
    status: "draft",
  },
  {
    id: "origin-grand-architect",
    name: "Grand Architect",
    type: "origin",
    tags: [],
    effect:
      "Your Reality. Construct Pandora's Box. This can only be used once you use a vault. You can upgrade your Pandora's Box by using better vaults.",
    source: "1.4 BRUNO.pdf p.9",
    status: "draft",
  },
  {
    id: "origin-masterchef",
    name: "Masterchef",
    type: "origin",
    tags: [],
    effect:
      "Let him Cook. You're cooking a food and can keep perfecting it. Red cards will speed up your cooking by 1 round. Serving your dish early will end your Masterpiece.",
    source: "1.4 BRUNO.pdf p.9",
    status: "draft",
  },
  {
    id: "origin-fateweaver",
    name: "Fateweaver",
    type: "origin",
    tags: [],
    effect:
      "Winners mindset. Have a slot machine, you can spin it as many times depending on your card.",
    source: "1.4 BRUNO.pdf p.9",
    status: "draft",
  },

  // ---- Artifacts (p.3-4) ----
  {
    id: "artifact-boot",
    name: "Boot",
    type: "artifact",
    tags: [],
    effect: "Powerful magic withers from it…",
    source: "1.4 BRUNO.pdf p.3",
    status: "draft",
  },
  {
    id: "artifact-leg",
    name: "Leg",
    type: "artifact",
    tags: [],
    effect: "(mirror/upside-down flavor text on p.4, inverse of Boot's)",
    source: "1.4 BRUNO.pdf p.4",
    status: "draft",
  },
];

export const VAULT_TIER_COUNTS = {
  "vault-silver": 27,
  "vault-gold": 21,
  "vault-diamond": 42,
} as const;
